package com.gameiq.repository

import com.gameiq.entity.WorkoutPlan
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.query.Param
import org.springframework.stereotype.Repository
import java.time.LocalDateTime

@Repository
interface WorkoutPlanRepository : JpaRepository<WorkoutPlan, Long> {
    
    // Get all workout plans for a user
    fun findByUserIdOrderByCreatedAtDesc(userId: Long): List<WorkoutPlan>
    
    // Get saved workout plans for a user
    fun findByUserIdAndIsSavedTrueOrderByCreatedAtDesc(userId: Long): List<WorkoutPlan>
    
    // Get workout plans by sport and position for a user
    fun findByUserIdAndSportAndPositionOrderByCreatedAtDesc(
        userId: Long, 
        sport: String, 
        position: String
    ): List<WorkoutPlan>
    
    // Get recent workout plans (last 7 days) for a user
    @Query("SELECT w FROM WorkoutPlan w WHERE w.userId = :userId AND w.createdAt >= :since ORDER BY w.createdAt DESC")
    fun findRecentWorkoutPlans(
        @Param("userId") userId: Long,
        @Param("since") since: LocalDateTime
    ): List<WorkoutPlan>
    
    // Count total workout plans generated by user
    fun countByUserId(userId: Long): Long
    
    // Count saved workout plans by user
    fun countByUserIdAndIsSavedTrue(userId: Long): Long
}